DELETE FROM payment WHERE label LIKE 'test%';
DELETE FROM payment WHERE REPLACE(paymentMonth, '-', '') > IF( DAYOFMONTH(CURDATE()) > 24, DATE_FORMAT(DATE_ADD(CURDATE(), INTERVAL 2 MONTH), '%Y%m'), DATE_FORMAT(DATE_ADD(CURDATE(), INTERVAL 1 MONTH), '%Y%m') );
TRUNCATE TABLE evolution;
